require "import"
import "android.app.*"
import "android.os.*"
import "android.widget.*"
import "android.view.*"
import "weibox"
import "androidx.viewpager.widget.ViewPager"
import "com.google.android.material.tabs.TabLayout"
import "android.animation.LayoutTransition"
import "com.nex3z.flowlayout.FlowLayout"



if(activity.getSharedData("外观风格")==0)then

  layout=
  {
    DrawerLayout;--侧滑布局
    layout_width='fill';--布局宽度
    layout_height='fill';--布局高度
    id='drawerLayout';--控件ID
    --主页面开始
    {
      LinearLayout;--线性控件
      orientation='vertical';--布局方向
      layout_width='fill';--布局宽度
      layout_height='fill';--布局高度
      background=卡片色;--布局背景
      --状态栏开始
      {
        LinearLayout;--线性控件
        orientation='horizontal';--布局方向
        layout_width='fill';--布局宽度
        layout_height=获取状态栏高度();--布局高度
        background=顶栏背景色;--布局背景
      };
      --状态栏结束
      --顶栏开始
      {
        LinearLayout;--线性控件
        orientation='horizontal';--布局方向
        layout_width='fill';--布局宽度
        layout_height='60dp';--布局高度
        background=顶栏背景色;--布局背景
        gravity='center';--控件内容的重力方向
        --左:left 右:right 中:center 顶:top 底:bottom
        --菜单按钮开始
        {
          LinearLayout;--线性控件
          orientation='vertical';--布局方向
          layout_width='30dp';--布局宽度
          layout_height='30dp';--布局高度
          gravity='center';--控件内容的重力方向
          --左:left 右:right 中:center 顶:top 底:bottom
          id='menu';--控件ID
          layout_margin='10dp';--控件外边距
          {
            LinearLayout;
            background=顶栏主文本色;
            layout_width="22dp";
            id="menu1";
            layout_margin="2dp";
            layout_height="2.5dp";
          };
          {
            LinearLayout;
            background=顶栏主文本色;
            layout_width="22dp";
            id="menu2";
            layout_margin="2dp";
            layout_height="2.5dp";
          };
          {
            LinearLayout;
            background=顶栏主文本色;
            layout_width="22dp";
            id="menu3";
            layout_margin="2dp";
            layout_height="2.5dp";
          };
        };
        --菜单按钮结束
        --标题开始
        {
          LinearLayout;--线性控件
          orientation='vertical';--布局方向
          layout_width='fill';--布局宽度
          layout_height='55dp';--布局高度
          gravity='center';--控件内容的重力方向
          --左:left 右:right 中:center 顶:top 底:bottom
          layout_margin='5dp';--控件外边距
          layout_weight='1';--权重值
          {
            TextView;--文本控件
            layout_width='fill';--控件宽度
            layout_height='wrap';--控件高度
            text=应用名称;--显示文字
            textSize='18sp';--文字大小
            textColor=顶栏主文本色;--文字颜色
            id='title';--设置控件ID
            singleLine=true;--设置单行输入
            ellipsize='end';--多余文字用省略号显示
            --start 开始 middle 中间 end 结尾
            --Typeface=Typeface.DEFAULT;--字体
            --textIsSelectable=true;--文本可复制
            --style="?android:attr/buttonBarButtonStyle";--点击特效
            gravity='center|left';--重力
            --左:left 右:right 中:center 顶:top 底:bottom
          };
          {
            TextView;--文本控件
            layout_width='fill';--控件宽度
            layout_height='wrap';--控件高度
            text='加载中…';--显示文字
            textSize='14sp';--文字大小
            textColor=顶栏辅文本色;--文字颜色
            id='subtitle';--设置控件ID
            singleLine=true;--设置单行输入
            ellipsize='end';--多余文字用省略号显示
            --start 开始 middle 中间 end 结尾
            --Typeface=Typeface.DEFAULT;--字体
            --textIsSelectable=true;--文本可复制
            --style="?android:attr/buttonBarButtonStyle";--点击特效
            gravity='center|left';--重力
            --左:left 右:right 中:center 顶:top 底:bottom
          };
        };
        --标题结束
        --搜索按钮开始
        {
          LinearLayout;--线性控件
          orientation='horizontal';--布局方向
          layout_width='30dp';--布局宽度
          layout_height='30dp';--布局高度
          gravity='center';--控件内容的重力方向
          --左:left 右:right 中:center 顶:top 底:bottom
          id='search';--控件ID
          layout_margin='10dp';--控件外边距
          {
            ImageView;--图片控件
            layout_width='25dp';--图片宽度
            layout_height='25dp';--图片高度
            src='drawable/search_black.png';--图片路径
            --id='Image';--设置控件ID
            ColorFilter=顶栏主文本色;--图片着色
            --ColorFilter=Color.BLUE;--设置图片着色
            scaleType='fitXY';--图片拉伸
            layout_gravity='center';--重力
          };
        };
        --搜索按钮结束
      };
      --顶栏结束
      --标签栏开始
      {
        TabLayout,
        layout_width='fill';--控件宽度
        layout_height='wrap';--控件高度
        id="tablayout";--设置控件ID
        background=卡片色;--布局背景
        tabIndicatorFullWidth=false;
        tabMode=TabLayout.MODE_SCROLLABLE;
        layoutTransition=LayoutTransition().enableTransitionType(LayoutTransition.CHANGING)
      };
      --标签栏结束
      {
        TextView;--横向分割线
        layout_width='fill';--分割线宽度
        layout_height='2px';--分割线厚度
        layout_gravity='center';--高度居中
        backgroundColor=分割线色;--分割线颜色
      };
      {
        PageView;--滑动视图
        layout_width='fill';--控件宽度
        layout_height='fill';--控件高度
        id="page";
        pages={
          --第一页开始
          {
            LinearLayout;--线性控件
            orientation='vertical';--布局方向
            layout_width='fill';--布局宽度
            layout_height='fill';--布局高度
            id='page1';--控件ID
          };
          --第一页结束
          --第二页开始
          {
            LinearLayout;--线性控件
            orientation='vertical';--布局方向
            layout_width='fill';--布局宽度
            layout_height='fill';--布局高度
            id='page2';--控件ID
          };
          --第二页结束
          --第三页开始
          {
            LinearLayout;--线性控件
            orientation='vertical';--布局方向
            layout_width='fill';--布局宽度
            layout_height='fill';--布局高度
            id='page3';--控件ID
          };
          --第三页结束
        };
      };
    };
    --主页面结束
    --侧滑栏开始
    {
      LinearLayout;--线性控件
      orientation='vertical';--布局方向
      layout_width='65%w';--布局宽度
      layout_height='fill';--布局高度
      background=卡片色;--布局背景
      layout_gravity="start";
      --状态栏开始
      {
        LinearLayout;--线性控件
        orientation='horizontal';--布局方向
        layout_width='fill';--布局宽度
        layout_height=获取状态栏高度();--布局高度
        background=顶栏背景色;--布局背景
      };
      --状态栏结束
      {
        TextView;--文本控件
        layout_width='wrap';--控件宽度
        layout_height='wrap';--控件高度
        text=应用名称;--显示文字
        textSize='30sp';--文字大小
        textColor=主文本色;--文字颜色
        --id='Text';--设置控件ID
        --singleLine=true;--设置单行输入
        --ellipsize='end';--多余文字用省略号显示
        --start 开始 middle 中间 end 结尾
        --Typeface=Typeface.DEFAULT;--字体
        --textIsSelectable=true;--文本可复制
        --style="?android:attr/buttonBarButtonStyle";--点击特效
        gravity='center';--重力
        --左:left 右:right 中:center 顶:top 底:bottom
        layout_margin='10dp';--控件外边距
        paddingLeft='5dp';--控件内左距
      };
      {
        ListView;--列表适配器
        layout_width='fill';--宽度
        layout_height='fill';--高度
        id="drawer_lv";
        DividerHeight=0;--分割线高度0为无隔断线
        --verticalScrollBarEnabled=false;--隐藏滑条
      };
    };
    --侧滑栏结束
  }

  activity.setContentView(loadlayout(layout))

  tablayout.addTab(tablayout.newTab().setText("收藏"))
  tablayout.addTab(tablayout.newTab().setText("功能"))
  tablayout.addTab(tablayout.newTab().setText("发现"))
  tablayout.setTabTextColors(转0x(辅文本色),转0x(主题色))
  tablayout.setSelectedTabIndicatorColor(转0x(主题色))
  tablayout.setTabRippleColor(ColorStateList.valueOf(转0x(波纹色)))
  tablayout.addOnTabSelectedListener(TabLayout.OnTabSelectedListener{
    onTabUnselected=function(tab)
      --Tab没有被选择事件
    end;
    onTabSelected=function(tab)
      --Tab被选择事件
      page.showPage(tablayout.getSelectedTabPosition())
    end;
    onTabReselected=function(tab)
      --Tab被再次选择事件
    end
  })
  page.addOnPageChangeListener(PageView.OnPageChangeListener{
    onPageScrollStateChanged=function(a)
      --页面状态改变事件
    end;
    onPageScrolled=function(a,b,c)
      --页面滑动事件
    end;
    onPageSelected=function(a)
      --页面选择事件
      tablayout.getTabAt(a).select()
      lightD(ch_table[a+2][1])--这个是更改侧滑栏里的高亮，ch_table在后面会定义，大概就是页面名称
    end
  })

  import "page1"
  import "page2"
  import "page3"

  波纹(menu,转0x(波纹色))
  波纹(search,转0x(波纹色))
  menu.onClick=function()
    drawerLayout.openDrawer(3)--打开侧滑栏
  end
  search.onClick=function()
    activity.newActivity("sub/all.lua")
  end

  ch_item_checked_background = GradientDrawable()
  .setShape(GradientDrawable.RECTANGLE)
  .setColor(转0x(主题色)-0xde000000)
  .setCornerRadii({0,0,dp2px(24),dp2px(24),dp2px(24),dp2px(24),0,0});

  --侧滑列表项目
  drawer_item={
    {--侧滑标题 (type1)
      LinearLayout;--线性控件
      orientation='horizontal';--布局方向
      layout_width='fill';--布局宽度
      layout_height='wrap';--布局高度
      {
        TextView;--文本控件
        layout_width='wrap';--控件宽度
        layout_height='wrap';--控件高度
        text='';--显示文字
        textSize='14sp';--文字大小
        textColor=主题色;--文字颜色
        id='title';--设置控件ID
        --singleLine=true;--设置单行输入
        --ellipsize='end';--多余文字用省略号显示
        --start 开始 middle 中间 end 结尾
        --Typeface=Typeface.DEFAULT;--字体
        --textIsSelectable=true;--文本可复制
        --style="?android:attr/buttonBarButtonStyle";--点击特效
        gravity='center|left';--重力
        --左:left 右:right 中:center 顶:top 底:bottom
        layout_marginLeft='10dp';--控件左距
        layout_marginTop='10dp';--控件顶距
      };
    };
    {--侧滑项目 (type2)
      LinearLayout;--线性控件
      orientation='horizontal';--布局方向
      layout_width='fill';--布局宽度
      layout_height='wrap';--布局高度
      gravity='center|left';--控件内容的重力方向
      --左:left 右:right 中:center 顶:top 底:bottom
      paddingLeft='5dp';--控件内左距
      {
        ImageView;--图片控件
        layout_width='30dp';--图片宽度
        layout_height='30dp';--图片高度
        --src=''-图片路径
        id='icon';--设置控件ID
        ColorFilter=主文本色;--图片着色
        --ColorFilter=Color.BLUE;--设置图片着色
        scaleType='fitXY';--图片拉伸
        layout_gravity='center';--重力
        layout_margin='10dp';--控件外边距
        padding='2.5dp';--控件内边距
      };
      {
        TextView;--文本控件
        layout_width='wrap';--控件宽度
        layout_height='wrap';--控件高度
        text='';--显示文字
        textSize='16sp';--文字大小
        textColor=主文本色;--文字颜色
        id='title';--设置控件ID
        --singleLine=true;--设置单行输入
        --ellipsize='end';--多余文字用省略号显示
        --start 开始 middle 中间 end 结尾
        Typeface=Typeface.DEFAULT_BOLD;--字体
        --textIsSelectable=true;--文本可复制
        --style="?android:attr/buttonBarButtonStyle";--点击特效
        gravity='center';--重力
        --左:left 右:right 中:center 顶:top 底:bottom
        layout_margin='10dp';--控件外边距
      };
    };
    {--侧滑项目_选中项 (type3)
      RelativeLayout;
      layout_width="-1";
      layout_height="48dp";
      {
        LinearLayout;
        layout_width="-1";
        layout_height="-1";
        layout_marginRight="8dp";
        BackgroundDrawable=ch_item_checked_background;
      };
      {
        LinearLayout;--线性控件
        orientation='horizontal';--布局方向
        layout_width='fill';--布局宽度
        layout_height='wrap';--布局高度
        gravity='center|left';--控件内容的重力方向
        --左:left 右:right 中:center 顶:top 底:bottom
        paddingLeft='5dp';--控件内左距
        {
          ImageView;--图片控件
          layout_width='30dp';--图片宽度
          layout_height='30dp';--图片高度
          --src=''-图片路径
          id='icon';--设置控件ID
          ColorFilter=主题色;--图片着色
          --ColorFilter=Color.BLUE;--设置图片着色
          scaleType='fitXY';--图片拉伸
          layout_gravity='center';--重力
          layout_margin='10dp';--控件外边距
          padding='2.5dp';--控件内边距
        };
        {
          TextView;--文本控件
          layout_width='wrap';--控件宽度
          layout_height='wrap';--控件高度
          text='';--显示文字
          textSize='16sp';--文字大小
          textColor=主题色;--文字颜色
          id='title';--设置控件ID
          --singleLine=true;--设置单行输入
          --ellipsize='end';--多余文字用省略号显示
          --start 开始 middle 中间 end 结尾
          Typeface=Typeface.DEFAULT_BOLD;--字体
          --textIsSelectable=true;--文本可复制
          --style="?android:attr/buttonBarButtonStyle";--点击特效
          gravity='center';--重力
          --左:left 右:right 中:center 顶:top 底:bottom
          layout_margin='10dp';--控件外边距
        };
      };
    };
    {--侧滑_分割线 (type4)
      LinearLayout;--线性控件
      orientation='horizontal';--布局方向
      layout_width='fill';--布局宽度
      layout_height='wrap';--布局高度
      onClick=function()end;--防止分割线被点击
      {
        TextView;--横向分割线
        layout_width='fill';--分割线宽度
        layout_height='2px';--分割线厚度
        layout_gravity='center';--高度居中
        backgroundColor=分割线色;--分割线颜色
        layout_marginTop='10dp';--布局顶距
        layout_marginBottom='10dp';--布局底距
      };
    };
  };
  --侧滑列表适配器
  drawer_adp=LuaMultiAdapter(activity,drawer_item)
  drawer_lv.setAdapter(drawer_adp)
  --侧滑项目
  ch_table={
    "分割线",
    {"收藏","drawable/star_black.png",},
    {"功能","drawable/widgets_black.png",},
    {"发现","drawable/explore_black.png",},
    "分割线",
    {"应用设置","drawable/settings_black.png",},
    {"关于应用","drawable/info_black.png",},
  };
  function lightD(n)
    drawer_adp.clear()
    for i,v in ipairs(ch_table) do
      if(v=="分割线")then
        drawer_adp.add{__type=4}
       elseif(n==v[1])then
        drawer_adp.add{__type=3,title=v[1],icon={src=v[2]}}
       else
        drawer_adp.add{__type=2,title=v[1],icon={src=v[2]}}
      end
    end
  end
  lightD("功能")
  page.showPage(activity.getSharedData("启动页"))

  --侧滑列表点击事件
  drawer_lv.setOnItemClickListener(AdapterView.OnItemClickListener{
    onItemClick=function(parent,v,zero,one)
      --项目点击事件
      if(v.Tag.title.Text=="收藏")then
        page.showPage(0)
        drawerLayout.closeDrawer(3)--关闭侧滑
      end
      if(v.Tag.title.Text=="功能")then
        page.showPage(1)
        drawerLayout.closeDrawer(3)--关闭侧滑
      end
      if(v.Tag.title.Text=="发现")then
        page.showPage(2)
        drawerLayout.closeDrawer(3)--关闭侧滑
      end
      if(v.Tag.title.Text=="应用设置")then
        activity.newActivity("sub/settings.lua")
        退出页面()
      end
      if(v.Tag.title.Text=="关于应用")then
        activity.newActivity("sub/about.lua")
      end
    end
  })

  --侧滑栏列表动画
  drawerLayout.setScrimColor(0)--去除侧滑栏阴影
  drawerLayout.setDrawerListener(DrawerLayout.DrawerListener{
    onDrawerSlide=function(v,i)
      drawerLayout.getChildAt(1).setTranslationX(i)--侧滑栏滑动
      drawerLayout.getChildAt(0).setTranslationX(i*activity.getWidth()*0.65)--主界面滑动
      --菜单按钮动画
      local ii="2"-i
      local fffy
      menu1.Rotation=i*45
      menu3.Rotation=-i*45
      menu1.scaleX=(1-i/2.2)
      menu3.scaleX=(1-i/2.2)
      menu2.scaleX=(1-i/6)
      menu2.setTranslationX(-i*9)
      menu1.setTranslationY(i*4)
      menu3.setTranslationY(-i*4)
      if i*"180"==180.0 then
        fffy=3
      end
      if i*"180"==0.0 then
        fffy=nil
      end
      if fffy==nil then
        menu.Rotation=i*180
      end
      if fffy==3 then
        if ii==0.0 then
          ii=1
        end
        menu.Rotation=ii*180
      end
    end
  })
end



if(activity.getSharedData("外观风格")==1)then

  layout=
  {
    DrawerLayout;--侧滑布局
    layout_width='fill';--布局宽度
    layout_height='fill';--布局高度
    id='drawerLayout';--控件ID
    --主页面开始
    {
      LinearLayout;--线性控件
      orientation='vertical';--布局方向
      layout_width='fill';--布局宽度
      layout_height='fill';--布局高度
      background=背景色;--布局背景
      --状态栏开始
      {
        LinearLayout;--线性控件
        orientation='horizontal';--布局方向
        layout_width='fill';--布局宽度
        layout_height=获取状态栏高度();--布局高度
        background=顶栏背景色;--布局背景
      };
      --状态栏结束
      --顶栏开始
      {
        LinearLayout;--线性控件
        orientation='horizontal';--布局方向
        layout_width='fill';--布局宽度
        layout_height='56dp';--布局高度
        background=顶栏背景色;--布局背景
        gravity='center';--控件内容的重力方向
        --左:left 右:right 中:center 顶:top 底:bottom
        elevation='4dp';--阴影层次
        --菜单按钮开始
        {
          LinearLayout;--线性控件
          orientation='horizontal';--布局方向
          layout_width='30dp';--布局宽度
          layout_height='30dp';--布局高度
          gravity='center';--控件内容的重力方向
          --左:left 右:right 中:center 顶:top 底:bottom
          id='menu';--控件ID
          layout_margin='10dp';--控件外边距
          {
            ImageView;--图片控件
            layout_width='25dp';--图片宽度
            layout_height='25dp';--图片高度
            src='drawable/menu_black.png';--图片路径
            --id='Image';--设置控件ID
            ColorFilter=顶栏主文本色;--图片着色
            --ColorFilter=Color.BLUE;--设置图片着色
            scaleType='fitXY';--图片拉伸
            layout_gravity='center';--重力
          };
        };
        --菜单按钮结束
        --标题开始
        {
          LinearLayout;--线性控件
          orientation='vertical';--布局方向
          layout_width='fill';--布局宽度
          layout_height='55dp';--布局高度
          gravity='center';--控件内容的重力方向
          --左:left 右:right 中:center 顶:top 底:bottom
          layout_margin='5dp';--控件外边距
          layout_weight='1';--权重值
          {
            TextView;--文本控件
            layout_width='fill';--控件宽度
            layout_height='wrap';--控件高度
            text=应用名称;--显示文字
            textSize='20sp';--文字大小
            textColor=顶栏主文本色;--文字颜色
            id='title';--设置控件ID
            singleLine=true;--设置单行输入
            ellipsize='end';--多余文字用省略号显示
            --start 开始 middle 中间 end 结尾
            --Typeface=Typeface.DEFAULT;--字体
            --textIsSelectable=true;--文本可复制
            --style="?android:attr/buttonBarButtonStyle";--点击特效
            gravity='center|left';--重力
            --左:left 右:right 中:center 顶:top 底:bottom
          };
          {
            TextView;--文本控件
            layout_width='fill';--控件宽度
            layout_height='wrap';--控件高度
            text='加载中…';--显示文字
            textSize='12sp';--文字大小
            textColor=顶栏辅文本色;--文字颜色
            id='subtitle';--设置控件ID
            singleLine=true;--设置单行输入
            ellipsize='end';--多余文字用省略号显示
            --start 开始 middle 中间 end 结尾
            --Typeface=Typeface.DEFAULT;--字体
            --textIsSelectable=true;--文本可复制
            --style="?android:attr/buttonBarButtonStyle";--点击特效
            gravity='center|left';--重力
            --左:left 右:right 中:center 顶:top 底:bottom
          };
        };
        --标题结束
        --搜索按钮开始
        {
          LinearLayout;--线性控件
          orientation='horizontal';--布局方向
          layout_width='30dp';--布局宽度
          layout_height='30dp';--布局高度
          gravity='center';--控件内容的重力方向
          --左:left 右:right 中:center 顶:top 底:bottom
          id='search';--控件ID
          layout_margin='10dp';--控件外边距
          {
            ImageView;--图片控件
            layout_width='25dp';--图片宽度
            layout_height='25dp';--图片高度
            src='drawable/search_black.png';--图片路径
            --id='Image';--设置控件ID
            ColorFilter=顶栏主文本色;--图片着色
            --ColorFilter=Color.BLUE;--设置图片着色
            scaleType='fitXY';--图片拉伸
            layout_gravity='center';--重力
          };
        };
        --搜索按钮结束
      };
      --顶栏结束
      {
        ScrollView,
        layout_width='fill';
        layout_height='fill';
        verticalScrollBarEnabled=false;--隐藏纵向滑条
        overScrollMode=View.OVER_SCROLL_NEVER,--隐藏圆弧阴影
        {
          LinearLayout;--线性控件
          orientation='vertical';--布局方向
          layout_width='fill';--布局宽度
          layout_height='fill';--布局高度
          id='mainlinear';--设置控件ID
          layoutTransition=LayoutTransition()
          .enableTransitionType(LayoutTransition.CHANGING)
          .setDuration(LayoutTransition.CHANGE_APPEARING,300)
          .setDuration(LayoutTransition.CHANGE_DISAPPEARING,300),
          --卡片一开始
          {
            LinearLayout;--线性控件
            orientation='horizontal';--布局方向
            layout_width='fill';--布局宽度
            layout_height='60dp';--布局高度
            background=卡片色;--布局背景
            gravity='center';--控件内容的重力方向
            --左:left 右:right 中:center 顶:top 底:bottom
            --全部功能开始
            {
              CardView;--卡片控件
              layout_width='50%w';--卡片宽度
              layout_height='fill';--卡片高度
              cardBackgroundColor=卡片色;--卡片颜色
              cardElevation='0dp';--卡片阴影
              radius='0dp';--卡片圆角
              {
                LinearLayout;--线性控件
                orientation='horizontal';--布局方向
                layout_width='fill';--布局宽度
                layout_height='fill';--布局高度
                gravity='center';--控件内容的重力方向
                --左:left 右:right 中:center 顶:top 底:bottom
                id='all';--设置控件ID
                paddingLeft='10dp';--控件内左距
                {
                  ImageView;--图片控件
                  layout_width='30dp';--图片宽度
                  layout_height='30dp';--图片高度
                  src='drawable/apps_black.png';--图片路径
                  --id='Image';--设置控件ID
                  ColorFilter='#FF83B1EA';--图片着色
                  --ColorFilter=Color.BLUE;--设置图片着色
                  --scaleType='fitXY';--图片拉伸
                  --layout_gravity='center';--重力
                };
                {
                  TextView;--文本控件
                  layout_width='fill';--控件宽度
                  layout_height='wrap';--控件高度
                  text='更多功能';--显示文字
                  textSize='18sp';--文字大小
                  textColor=主文本色;--文字颜色
                  --id='Text';--设置控件ID
                  --singleLine=true;--设置单行输入
                  --ellipsize='end';--多余文字用省略号显示
                  --start 开始 middle 中间 end 结尾
                  --Typeface=Typeface.DEFAULT;--字体
                  --textIsSelectable=true;--文本可复制
                  --style="?android:attr/buttonBarButtonStyle";--点击特效
                  layout_marginLeft='5dp';--布局左距
                  gravity='center|left';--重力
                  --左:left 右:right 中:center 顶:top 底:bottom
                };
              };
            };
            --全部功能结束
            {
              TextView;--纵向分割线
              layout_width='3px';--分割线宽度
              layout_height='20dp';--分割线厚度
              layout_gravity='center';--高度居中
              backgroundColor=分割线色;--分割线颜色
            };
            --我的收藏开始
            {
              CardView;--卡片控件
              layout_width='50%w';--卡片宽度
              layout_height='fill';--卡片高度
              cardBackgroundColor=卡片色;--卡片颜色
              cardElevation='0dp';--卡片阴影
              radius='0dp';--卡片圆角
              {
                LinearLayout;--线性控件
                orientation='horizontal';--布局方向
                layout_width='fill';--布局宽度
                layout_height='fill';--布局高度
                gravity='center';--控件内容的重力方向
                --左:left 右:right 中:center 顶:top 底:bottom
                id='favorite';--设置控件ID
                paddingLeft='10dp';--控件内左距
                {
                  ImageView;--图片控件
                  layout_width='30dp';--图片宽度
                  layout_height='30dp';--图片高度
                  src='drawable/star_black.png';--图片路径
                  --id='Image';--设置控件ID
                  ColorFilter='#FFFAE251';--图片着色
                  --ColorFilter=Color.BLUE;--设置图片着色
                  --scaleType='fitXY';--图片拉伸
                  --layout_gravity='center';--重力
                };
                {
                  TextView;--文本控件
                  layout_width='fill';--控件宽度
                  layout_height='wrap';--控件高度
                  text='收藏功能';--显示文字
                  textSize='18sp';--文字大小
                  textColor=主文本色;--文字颜色
                  --id='Text';--设置控件ID
                  --singleLine=true;--设置单行输入
                  --ellipsize='end';--多余文字用省略号显示
                  --start 开始 middle 中间 end 结尾
                  --Typeface=Typeface.DEFAULT;--字体
                  --textIsSelectable=true;--文本可复制
                  --style="?android:attr/buttonBarButtonStyle";--点击特效
                  layout_marginLeft='5dp';--布局左距
                  gravity='center|left';--重力
                  --左:left 右:right 中:center 顶:top 底:bottom
                };
              };
            };
            --我的收藏结束
          };
          --卡片一结束
          --剩下的在后面，动态添加
        };
      };
    };
    --主页面结束
    --侧滑栏开始
    {
      LinearLayout;--线性控件
      orientation='vertical';--布局方向
      layout_width='70%w';--布局宽度
      layout_height='fill';--布局高度
      background=卡片色;--布局背景
      layout_gravity="start";
      --状态栏开始
      {
        LinearLayout;--线性控件
        orientation='horizontal';--布局方向
        layout_width='fill';--布局宽度
        layout_height=获取状态栏高度();--布局高度
        background=卡片色;--布局背景
        gravity='center';--控件内容的重力方向
        id='drawer_status';--设置控件ID
      };
      --状态栏结束
      {
        LinearLayout;--线性控件
        orientation='vertical';--布局方向
        layout_width='fill';--布局宽度
        layout_height='wrap';--布局高度
        background=卡片色;--布局背景
        gravity='left|center';--控件内容的重力方向
        --左:left 右:right 中:center 顶:top 底:bottom
        id='drawer_background';--设置控件ID
        paddingBottom='5dp';--控件内底距
        {
          ImageView;--图片控件
          layout_width='60dp';--图片宽度
          layout_height='60dp';--图片高度
          src=应用图标;--图片路径
          --id='Image';--设置控件ID
          --ColorFilter='';--图片着色
          --ColorFilter=Color.BLUE;--设置图片着色
          scaleType='fitXY';--图片拉伸
          layout_gravity='center|left';--重力
          layout_margin='5dp';--控件外边距
          layout_marginLeft='15dp';--控件左距
        };
        {
          TextView;--文本控件
          layout_width='wrap';--控件宽度
          layout_height='wrap';--控件高度
          text=应用名称;--显示文字
          textSize='22sp';--文字大小
          textColor=顶栏主文本色;--文字颜色
          --id='Text';--设置控件ID
          --singleLine=true;--设置单行输入
          --ellipsize='end';--多余文字用省略号显示
          --start 开始 middle 中间 end 结尾
          Typeface=Typeface.DEFAULT_BOLD;--字体
          --textIsSelectable=true;--文本可复制
          --style="?android:attr/buttonBarButtonStyle";--点击特效
          gravity='center';--重力
          --左:left 右:right 中:center 顶:top 底:bottom
          layout_margin='2dp';--控件外边距
          layout_marginLeft='15dp';--控件左距
        };
        {
          TextView;--文本控件
          layout_width='wrap';--控件宽度
          layout_height='wrap';--控件高度
          text=应用标语;--显示文字
          textSize='13sp';--文字大小
          textColor=顶栏辅文本色;--文字颜色
          --id='Text';--设置控件ID
          --singleLine=true;--设置单行输入
          --ellipsize='end';--多余文字用省略号显示
          --start 开始 middle 中间 end 结尾
          --Typeface=Typeface.DEFAULT;--字体
          --textIsSelectable=true;--文本可复制
          --style="?android:attr/buttonBarButtonStyle";--点击特效
          gravity='center';--重力
          --左:left 右:right 中:center 顶:top 底:bottom
          layout_margin='2dp';--控件外边距
          layout_marginLeft='15dp';--控件左距
        };
      };
      {
        ListView;--列表适配器
        layout_width='fill';--宽度
        layout_height='fill';--高度
        id="drawer_lv";
        DividerHeight=0;--分割线高度0为无隔断线
        --verticalScrollBarEnabled=false;--隐藏滑条
      };
    };
    --侧滑栏结束
  }

  activity.setContentView(loadlayout(layout))

  波纹(menu,转0x(波纹色))
  波纹(search,转0x(波纹色))
  波纹(all,转0x(波纹色))
  波纹(favorite,转0x(波纹色))
  menu.onClick=function()
    drawerLayout.openDrawer(3)--打开侧滑栏
  end
  search.onClick=function()
    activity.newActivity("sub/all.lua")
  end
  all.onClick=function()
    activity.newActivity("sub/all.lua")
  end
  favorite.onClick=function()
    activity.newActivity("sub/favorite.lua")
  end

  drawer_background.setBackgroundColor(转0x(主题色)-0x30000000)
  drawer_status.setBackgroundColor(转0x(主题色)-0x30000000)

  --侧滑列表项目
  drawer_item={
    {--侧滑标题 (type1)
      LinearLayout;--线性控件
      orientation='horizontal';--布局方向
      layout_width='fill';--布局宽度
      layout_height='wrap';--布局高度
      {
        TextView;--文本控件
        layout_width='wrap';--控件宽度
        layout_height='wrap';--控件高度
        text='';--显示文字
        textSize='14sp';--文字大小
        textColor=主题色;--文字颜色
        id='title';--设置控件ID
        --singleLine=true;--设置单行输入
        --ellipsize='end';--多余文字用省略号显示
        --start 开始 middle 中间 end 结尾
        --Typeface=Typeface.DEFAULT;--字体
        --textIsSelectable=true;--文本可复制
        --style="?android:attr/buttonBarButtonStyle";--点击特效
        gravity='center|left';--重力
        --左:left 右:right 中:center 顶:top 底:bottom
        layout_marginLeft='10dp';--控件左距
        layout_marginTop='10dp';--控件顶距
      };
    };
    {--侧滑项目 (type2)
      LinearLayout;--线性控件
      orientation='horizontal';--布局方向
      layout_width='fill';--布局宽度
      layout_height='wrap';--布局高度
      gravity='center|left';--控件内容的重力方向
      --左:left 右:right 中:center 顶:top 底:bottom
      paddingLeft='5dp';--控件内左距
      padding='2dp';--控件内边距
      {
        ImageView;--图片控件
        layout_width='30dp';--图片宽度
        layout_height='30dp';--图片高度
        --src=''-图片路径
        id='icon';--设置控件ID
        ColorFilter=辅文本色;--图片着色
        --ColorFilter=Color.BLUE;--设置图片着色
        scaleType='fitXY';--图片拉伸
        layout_gravity='center';--重力
        layout_margin='10dp';--控件外边距
        padding='2.5dp';--控件内边距
      };
      {
        TextView;--文本控件
        layout_width='wrap';--控件宽度
        layout_height='wrap';--控件高度
        text='';--显示文字
        textSize='14sp';--文字大小
        textColor=主文本色;--文字颜色
        id='title';--设置控件ID
        --singleLine=true;--设置单行输入
        --ellipsize='end';--多余文字用省略号显示
        --start 开始 middle 中间 end 结尾
        --Typeface=Typeface.DEFAULT;--字体
        --textIsSelectable=true;--文本可复制
        --style="?android:attr/buttonBarButtonStyle";--点击特效
        gravity='center';--重力
        --左:left 右:right 中:center 顶:top 底:bottom
        layout_margin='10dp';--控件外边距
      };
    };
    {--侧滑项目_选中项 (type3)
      RelativeLayout;
      layout_width="-1";
      layout_height="48dp";
      {
        LinearLayout;
        layout_width="-1";
        layout_height="-1";
        layout_marginRight="8dp";
        BackgroundDrawable=ch_item_checked_background;
      };
      {
        LinearLayout;--线性控件
        orientation='horizontal';--布局方向
        layout_width='fill';--布局宽度
        layout_height='wrap';--布局高度
        gravity='center|left';--控件内容的重力方向
        --左:left 右:right 中:center 顶:top 底:bottom
        paddingLeft='5dp';--控件内左距
        padding='2dp';--控件内边距
        {
          ImageView;--图片控件
          layout_width='30dp';--图片宽度
          layout_height='30dp';--图片高度
          --src=''-图片路径
          id='icon';--设置控件ID
          ColorFilter=主题色;--图片着色
          --ColorFilter=Color.BLUE;--设置图片着色
          scaleType='fitXY';--图片拉伸
          layout_gravity='center';--重力
          layout_margin='10dp';--控件外边距
          padding='2.5dp';--控件内边距
        };
        {
          TextView;--文本控件
          layout_width='wrap';--控件宽度
          layout_height='wrap';--控件高度
          text='';--显示文字
          textSize='14sp';--文字大小
          textColor=主题色;--文字颜色
          id='title';--设置控件ID
          --singleLine=true;--设置单行输入
          --ellipsize='end';--多余文字用省略号显示
          --start 开始 middle 中间 end 结尾
          --Typeface=Typeface.DEFAULT;--字体
          --textIsSelectable=true;--文本可复制
          --style="?android:attr/buttonBarButtonStyle";--点击特效
          gravity='center';--重力
          --左:left 右:right 中:center 顶:top 底:bottom
          layout_margin='10dp';--控件外边距
        };
      };
    };
    {--侧滑_分割线 (type4)
      LinearLayout;--线性控件
      orientation='horizontal';--布局方向
      layout_width='fill';--布局宽度
      layout_height='wrap';--布局高度
      onClick=function()end;--防止分割线被点击
      {
        TextView;--横向分割线
        layout_width='fill';--分割线宽度
        layout_height='2px';--分割线厚度
        layout_gravity='center';--高度居中
        backgroundColor=分割线色;--分割线颜色
        layout_marginTop='5dp';--布局顶距
        layout_marginBottom='5dp';--布局底距
      };
    };
  };
  --侧滑列表适配器
  drawer_adp=LuaMultiAdapter(activity,drawer_item)
  drawer_lv.setAdapter(drawer_adp)
  --侧滑项目
  ch_table={
    {"更多功能","drawable/apps_black.png",},
    {"收藏功能","drawable/star_black.png",},
    "分割线",
    {"应用设置","drawable/settings_black.png",},
    {"关于应用","drawable/info_black.png",},
  };
  for i,v in ipairs(ch_table) do
    if(v=="分割线")then
      drawer_adp.add{__type=4}
     elseif(n==v[1])then
      drawer_adp.add{__type=3,title=v[1],icon={src=v[2]}}
     else
      drawer_adp.add{__type=2,title=v[1],icon={src=v[2]}}
    end
  end

  --侧滑列表点击事件
  drawer_lv.setOnItemClickListener(AdapterView.OnItemClickListener{
    onItemClick=function(parent,v,zero,one)
      --项目点击事件
      drawerLayout.closeDrawer(3)--关闭侧滑
      if(v.Tag.title.Text=="更多功能")then
        activity.newActivity("sub/all.lua")
      end
      if(v.Tag.title.Text=="收藏功能")then
        activity.newActivity("sub/favorite.lua")
      end
      if(v.Tag.title.Text=="应用设置")then
        activity.newActivity("sub/settings.lua")
        退出页面()
      end
      if(v.Tag.title.Text=="关于应用")then
        activity.newActivity("sub/about.lua")
      end
    end
  })

  function 展开(v)
    activity.setSharedData("page2"..v.."展开",true)
    _ENV["main"..v.."flow"].setVisibility(View.VISIBLE)
    _ENV["main"..v.."arrow"].setImageBitmap(loadbitmap("drawable/keyboard_arrow_down_black.png"))
  end
  function 折叠(v)
    activity.setSharedData("page2"..v.."展开",false)
    _ENV["main"..v.."flow"].setVisibility(View.GONE)
    _ENV["main"..v.."arrow"].setImageBitmap(loadbitmap("drawable/keyboard_arrow_right_black.png"))
  end

  function 添加功能组(编号,名称,图标)
    --初始化折叠状态
    if(activity.getSharedData("page2"..编号.."展开")==nil)then
      activity.setSharedData("page2"..编号.."展开",true)
    end
    功能组布局={
      LinearLayout;--线性控件
      orientation='vertical';--布局方向
      layout_width='fill';--布局宽度
      layout_height='wrap';--布局高度
      {
        CardView;--卡片控件
        layout_width='fill';--卡片宽度
        layout_height='wrap';--卡片高度
        cardBackgroundColor=卡片色;--卡片颜色
        cardElevation='0dp';--卡片阴影
        radius='0dp';--卡片圆角
        id='main'..编号;--设置控件ID
        layout_marginTop='10dp';--控件顶距
        {
          LinearLayout;--线性控件
          orientation='vertical';--布局方向
          layout_width='fill';--布局宽度
          layout_height='wrap';--布局高度
          gravity='center';--控件内容的重力方向
          --左:left 右:right 中:center 顶:top 底:bottom
          layoutTransition=LayoutTransition()
          .enableTransitionType(LayoutTransition.CHANGING)
          .setDuration(LayoutTransition.CHANGE_APPEARING,300)
          .setDuration(LayoutTransition.CHANGE_DISAPPEARING,300),
          {
            CardView;--卡片控件
            layout_width='fill';--卡片宽度
            layout_height='wrap';--卡片高度
            cardBackgroundColor=卡片色;--卡片颜色
            cardElevation='0dp';--卡片阴影
            radius='0dp';--卡片圆角
            {
              LinearLayout;--线性控件
              orientation='horizontal';--布局方向
              layout_width='fill';--布局宽度
              layout_height='fill';--布局高度
              gravity='center';--控件内容的重力方向
              --左:left 右:right 中:center 顶:top 底:bottom
              padding='10dp';--控件内边距
              id='main'..编号..'title';--设置控件ID
              background=列表波纹(转0x(波纹色));
              {
                ImageView;--图片控件
                layout_width='30dp';--图片宽度
                layout_height='30dp';--图片高度
                src=图标;--图片路径
                --id='Image';--设置控件ID
                ColorFilter=主题色;--图片着色
                --ColorFilter=Color.BLUE;--设置图片着色
                scaleType='fitXY';--图片拉伸
                layout_gravity='center';--重力
                layout_margin='5dp';--控件外边距
              };
              {
                TextView;--文本控件
                layout_width='fill';--控件宽度
                layout_height='wrap';--控件高度
                text=名称;--显示文字
                textSize='18sp';--文字大小
                textColor=主文本色;--文字颜色
                --id='Text';--设置控件ID
                --singleLine=true;--设置单行输入
                --ellipsize='end';--多余文字用省略号显示
                --start 开始 middle 中间 end 结尾
                --Typeface=Typeface.DEFAULT;--字体
                --textIsSelectable=true;--文本可复制
                --style="?android:attr/buttonBarButtonStyle";--点击特效
                gravity='center|left';--重力
                --左:left 右:right 中:center 顶:top 底:bottom
                layout_margin='5dp';--控件外边距
                layout_marginLeft='10dp';--布局左距
                layout_weight='1';--权重值
              };
              {
                ImageView;--图片控件
                layout_width='25dp';--图片宽度
                layout_height='25dp';--图片高度
                --src='';--图片路径
                id='main'..编号..'arrow';--设置控件ID
                ColorFilter=主题色;--图片着色
                --ColorFilter=Color.BLUE;--设置图片着色
                scaleType='fitXY';--图片拉伸
                layout_gravity='center';--重力
                layout_margin='5dp';--控件外边距
              };
            };
          };
          {
            FlowLayout;
            layout_width="fill";--布局宽度
            layout_height="fill";--布局高度
            MaxRows='4dp';
            MinChildSpacing='10dp';
            --自控力间距
            ChildSpacing='10dp';
            --行间距
            RowSpacing="10dp";
            id='main'..编号..'flow';--设置控件ID
            layout_margin='15dp';--控件外边距
            layout_marginTop='0dp';--控件顶距
          };
        };
      };
    }
    mainlinear.addView(loadlayout(功能组布局))
    if(activity.getSharedData("page2"..编号.."展开"))then
      展开(编号)
     else
      折叠(编号)
    end
    _ENV["main"..编号.."title"].onClick=function()
      if(activity.getSharedData("page2"..编号.."展开"))then
        折叠(编号)
        activity.setSharedData("page2"..编号.."展开",false)
       else
        展开(编号)
        activity.setSharedData("page2"..编号.."展开",true)
      end
    end
  end

  function 添加功能(编号,标题,类型,点击)
    if(类型=="1")then--类型1：普通
      文字颜色=主文本色
      文字类型=Typeface.DEFAULT
    end
    if(类型=="2")then--类型2：加粗
      文字颜色=主文本色
      文字类型=Typeface.DEFAULT_BOLD
    end
    if(类型=="3")then--类型3：强调
      文字颜色=主题色
      文字类型=Typeface.DEFAULT_BOLD
    end
    功能布局={
      LinearLayout;--线性控件
      orientation='horizontal';--布局方向
      layout_width='wrap';--布局宽度
      layout_height='wrap';--布局高度
      gravity='center';--控件内容的重力方向
      --左:left 右:right 中:center 顶:top 底:bottom
      BackgroundDrawable=CircleButton(转0x(背景色),90);
      {
        TextView;--文本控件
        layout_width='fill';--控件宽度
        layout_height='fill';--控件高度
        text=标题;--显示文字
        textSize='15sp';--文字大小
        textColor=文字颜色;--文字颜色
        id='mainitem';--设置控件ID
        --singleLine=true;--设置单行输入
        --ellipsize='end';--多余文字用省略号显示
        --start 开始 middle 中间 end 结尾
        Typeface=文字类型;--字体
        --textIsSelectable=true;--文本可复制
        --.style="?android:attr/buttonBarButtonStyle";--点击特效
        gravity='center';--重力
        --左:left 右:right 中:center 顶:top 底:bottom
        padding='7dp';--控件内边距
        layout_marginLeft='5dp';--控件左距
        layout_marginRight='5dp';--控件右距
        background=列表波纹(转0x(波纹色));
        onClick=点击;
        onLongClick=function()
          if not 获取收藏("收藏",标题) then
            local dialog=AlertDialog.Builder(this)
            .setTitle("收藏")
            .setMessage("要将"..标题.."添加到收藏中吗？")
            .setPositiveButton("确定",function()
              添加收藏("收藏",标题,string.dump(点击))
              弹出SnackBar("已将"..标题.."添加到收藏中")
            end)
            .setNegativeButton("取消",nil)
            .show()
            dialog.getButton(dialog.BUTTON_POSITIVE).setTextColor(转0x(主题色))
            dialog.getButton(dialog.BUTTON_NEGATIVE).setTextColor(转0x(主题色))
           else
            弹出SnackBar("该功能已在收藏中")
          end
        end
      };
    }

    _ENV["main"..编号.."flow"].addView(loadlayout(功能布局))
  end

  添加功能组("a","日常功能","drawable/wb_sunny_black.png")
  添加功能组("b","查询功能","drawable/search_black.png")
  添加功能组("c","图片功能","drawable/image_black.png")
  添加功能组("d","文字功能","drawable/text_fields_black.png")
  添加功能组("e","计算功能","drawable/exposure_black.png")
  添加功能组("f","影音功能","drawable/movie_black.png")
  添加功能组("g","设备功能","drawable/phone_android_black.png")
  添加功能组("h","其它功能","drawable/more_black.png")


  import "list"
  for i=1,#功能列表 do
    添加功能(功能列表[i][1],功能列表[i][2],功能列表[i][3],功能列表[i][4])
  end
end

--返回键
local 次数=0
function onKeyDown(code,event)
  if(code==4)then
    --侧滑栏重写过了，所以要自己判断是否打开
    if(drawerLayout.isDrawerOpen(3))then
      drawerLayout.closeDrawer(3)--关闭侧滑栏
     else
      if(次数+2>tonumber(os.time()))then
        退出页面()
       else
        弹出SnackBar("再按一次返回键退出软件")
        次数=tonumber(os.time())
      end
    end
    return true
  end
end